<?php
/**
 * Define @var $this Plumslice_Api_Block_Adminhtml_System_Config_Fieldset_Hint
 *
 */
?>
<div class="box">
    <div style="padding-left:55px;min-height:42px;">
        <h4><?php echo $this->helper('plumslice_api')->__('PlumSliceMagento extension extends SOAP v1.0 API for some of missing features required for Catalog Synching and searching functionality.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('plumslice_api')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('plumslice_api')->__('http://www.plumslice.com/')); ?>" target="_blank"><?php echo $this->helper('plumslice_api')->__('here'); ?></a>.</p>
    </div>
</div>